sources:
  openai_blog:
    url: https://openai.com/news/rss.xml
    type: rss
    category: Industry
    enabled: true
    description: OpenAI official news feed
  microsoft_ai_blog:
    url: https://blogs.microsoft.com/ai/feed/
    type: rss
    category: Industry
    enabled: true
    description: Microsoft AI blog
  azure_ai_blog:
    url: https://azure.microsoft.com/en-us/blog/feed/
    type: rss
    category: Industry
    enabled: true
    description: Azure AI Services Blog - Microsoft cloud AI updates
    legal_note: Non-commercial syndication permitted
  aws_ml_blog:
    url: https://aws.amazon.com/blogs/machine-learning/feed/
    type: rss
    category: Industry
    enabled: true
    description: AWS Machine Learning Blog - comprehensive ML/AI industry insights
    legal_note: Non-commercial syndication allowed
  nvidia_blog:
    url: https://blogs.nvidia.com/feed/
    type: rss
    category: Industry
    enabled: true
    description: NVIDIA AI blog
  datarobot_blog:
    url: https://datarobot.com/blog/feed/
    type: rss
    category: Industry
    enabled: true
    description: DataRobot Blog - automated machine learning platform insights
    legal_note: Non-commercial syndication allowed
  techcrunch_ai:
    url: https://techcrunch.com/category/artificial-intelligence/feed/
    type: rss
    category: Industry
    enabled: true
    description: TechCrunch AI news and analysis
  replicate_blog:
    url: https://replicate.com/blog/rss
    type: rss
    category: Industry
    enabled: true
    description: Replicate ML model hosting blog
  nvidia_developer:
    url: https://developer.nvidia.com/blog/feed/
    type: rss
    category: Industry
    enabled: true
    description: NVIDIA Developer Blog
  sequoia_ai:
    url: https://www.sequoiacap.com/feed/
    type: rss
    category: Startups
    enabled: true
    description: Sequoia Capital insights on AI and technology
  # Phase 2: Corporate research blogs (Industry, not academic papers)
  google_research_blog:
    url: https://research.google/blog/rss
    type: rss
    category: Industry
    enabled: true
    description: Google Research blog RSS - Corporate AI developments
    legal_note: Corporate content - not peer-reviewed academic papers
  
  deepmind_research:
    url: https://www.deepmind.com/blog/rss.xml
    type: rss
    category: Industry
    enabled: true
    description: DeepMind research announcements - Corporate AI blog
    legal_note: Corporate content - not peer-reviewed academic papers
  
  amazon_science:
    url: https://www.amazon.science/index.rss
    type: rss
    category: Industry
    enabled: true
    description: Amazon Science homepage - Corporate AI and ML developments
    legal_note: Corporate research content - not peer-reviewed papers
  
  google_ai_blog:
    url: http://googleaiblog.blogspot.com/atom.xml
    type: rss
    category: Industry
    enabled: true
    description: Google AI Blog - Corporate AI research and developments
    legal_note: Corporate content - not peer-reviewed academic papers
  anaconda_blog:
    url: https://www.anaconda.com/blog/feed
    type: rss
    category: Industry
    enabled: true
    description: Anaconda Blog - The Data Science Blog
  ai_techpark:
    url: https://ai-techpark.com/feed
    type: rss
    category: Industry
    enabled: true
    description: AI-TechPark - AI, ML, IoT, Cybersecurity News & Trend Analysis
  analytics_india_magazine:
    url: https://analyticsindiamag.com/feed/
    type: rss
    category: Industry
    enabled: true
    description: Analytics India Magazine - Emerging Tech, Artificial Intelligence, Data Science
  benzinga:
    url: https://www.benzinga.com/feed
    type: rss
    category: Industry
    enabled: true
    description: Benzinga - Financial and technology news
  dagshub_blog:
    url: https://dagshub.com/blog/rss/
    type: rss
    category: Industry
    enabled: true
    description: DagsHub Blog - Open Source Data Science, ML Workflows and MLOps
  dataconomy:
    url: https://dataconomy.com/feed
    type: rss
    category: Industry
    enabled: true
    description: Dataconomy - Bridging the gap between technology and business
  nanonets_blog:
    url: https://nanonets.com/blog/rss/
    type: rss
    category: Industry
    enabled: true
    description: AI & Machine Learning Blog - Nanonets AI Document Processing
  marktechpost:
    url: https://www.marktechpost.com/feed
    type: rss
    category: Industry
    enabled: true
    description: MarkTechPost - An Artificial Intelligence News Platform
  siliconangle_ai:
    url: https://siliconangle.com/category/ai/feed
    type: rss
    category: Industry
    enabled: true
    description: AI – SiliconANGLE - Enterprise technology news
  siliconangle_bigdata:
    url: https://siliconangle.com/category/big-data/feed
    type: rss
    category: Industry
    enabled: true
    description: Big Data – SiliconANGLE - Enterprise big data news
  synced:
    url: https://syncedreview.com/feed
    type: rss
    category: Industry
    enabled: true
    description: Synced - AI Technology & Industry Review
  ai_accelerator_institute:
    url: https://aiacceleratorinstitute.com/rss/
    type: rss
    category: Industry
    enabled: true
    description: AI Accelerator Institute - Future of Artificial Intelligence