sources:
  import_ai_substack:
    url: https://importai.substack.com/feed
    type: rss
    category: Media
    enabled: true
    description: Import AI by Jack Clark
  the_conversation:
    url: https://theconversation.com/articles.atom
    type: rss
    category: Media
    enabled: true
    description: The Conversation - academic experts writing for the public
    legal_note: CC BY-ND - republication allowed
  propublica_ai:
    url: https://www.propublica.org/feeds/propublica/main
    type: rss
    category: Media
    enabled: true
    description: ProPublica AI Coverage - investigative journalism on AI impact
    legal_note: CC BY-NC-ND 3.0 - republication allowed
  ai_news:
    url: https://www.artificialintelligence-news.com/feed/
    type: rss
    category: Media
    enabled: true
    description: AI News - dedicated AI journalism
  zdnet_ai:
    url: https://www.zdnet.com/topic/artificial-intelligence/rss.xml
    type: rss
    category: Media
    enabled: true
    description: ZDNet AI coverage
  forbes_ai:
    url: https://www.forbes.com/sites/bernardmarr/feed/
    type: rss
    category: Media
    enabled: true
    description: Forbes AI and Tech by Bernard Marr
  techcrunch_startups:
    url: https://techcrunch.com/category/startups/feed/
    type: rss
    category: Startups
    enabled: true
    description: TechCrunch Startups coverage - startup news and funding
    legal_note: Redistribution allowed with attribution
  crunchbase_news:
    url: https://news.crunchbase.com/feed
    type: rss
    category: Startups
    enabled: true
    description: Crunchbase News - startup funding and industry news
    legal_note: Standard RSS usage terms
  venturebeat_ai:
    url: https://venturebeat.com/ai/feed/
    type: rss
    category: Startups
    enabled: true
    description: VentureBeat AI business news
  crunchbase_ai:
    url: https://news.crunchbase.com/tag/artificial-intelligence/feed/
    type: rss
    category: Startups
    enabled: true
    description: Crunchbase AI funding and startup news
  the_gradient:
    url: https://thegradient.pub/rss/
    type: rss
    category: Media
    enabled: true
    description: The Gradient - AI research publication and commentary
    legal_note: Academic/non-commercial use friendly
  ai_now_institute:
    url: https://ainowinstitute.org/category/news/feed
    type: rss
    category: Media
    enabled: true
    description: AI Now Institute - AI ethics and social impact research
    legal_note: Check terms of service
  mit_ai_news:
    url: https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml
    type: rss
    category: Media
    enabled: true
    description: MIT AI research news and breakthroughs
  ieee_spectrum_ai:
    url: https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss
    type: rss
    category: Media
    enabled: true
    description: IEEE Spectrum AI coverage
  ieee_automaton_blog:
    url: https://spectrum.ieee.org/rss/blog/automaton
    type: rss
    category: Media
    enabled: true
    description: IEEE Spectrum Automaton blog (robotics and AI coverage)
    legal_note: Professional organization - check terms

  ars_technica:
    url: https://feeds.arstechnica.com/arstechnica/index
    type: rss
    category: Media
    enabled: true
    description: Ars Technica - Serving the Technologist for more than a decade
  dev_community:
    url: https://dev.to/feed
    type: rss
    category: Media
    enabled: true
    description: DEV Community - A constructive and inclusive social network for software developers
  digital_journal:
    url: https://www.digitaljournal.com/feed
    type: rss
    category: Media
    enabled: true
    description: Digital Journal - Digital media news network
  hacker_noon:
    url: https://hackernoon.com/tagged/ai/feed
    type: rss
    category: Media
    enabled: true
    description: Hacker Noon - AI tagged stories
  healthtech_magazine:
    url: https://feeds.feedburner.com/HealthTechMagazine
    type: rss
    category: Media
    enabled: true
    description: HealthTech Magazine - Healthcare technology news
  infoq_ai:
    url: https://feed.infoq.com/ai-ml-data-eng/
    type: rss
    category: Media
    enabled: true
    description: InfoQ - AI, ML & Data Engineering feed
  kdnuggets:
    url: https://www.kdnuggets.com/feed
    type: rss
    category: Media
    enabled: true
    description: KDnuggets - Machine Learning, Data Science, Big Data, Analytics, AI
  last_week_ai:
    url: https://lastweekin.ai/feed
    type: rss
    category: Media
    enabled: true
    description: Last Week in AI - Weekly digests of AI news
  new_scientist:
    url: https://www.newscientist.com/subject/technology/feed/
    type: rss
    category: Media
    enabled: true
    description: New Scientist - Technology news and analysis
  product_hunt:
    url: https://www.producthunt.com/feed
    type: rss
    category: Media
    enabled: true
    description: Product Hunt — The best new products, every day
  quanta_magazine:
    url: https://api.quantamagazine.org/feed
    type: rss
    category: Media
    enabled: true
    description: Quanta Magazine - Illuminating science
  rest_of_world:
    url: https://restofworld.org/feed/latest/
    type: rss
    category: Media
    enabled: true
    description: Rest of World - Reporting Global Tech Stories
  scientific_american:
    url: http://rss.sciam.com/ScientificAmerican-Global
    type: rss
    category: Media
    enabled: true
    description: Scientific American Content - Global science news
  tech_eu_deeptech:
    url: https://tech.eu/category/deep-tech/feed
    type: rss
    category: Media
    enabled: true
    description: Deep Tech - Tech.eu technology news
  tech_eu_robotics:
    url: https://tech.eu/category/robotics/feed
    type: rss
    category: Media
    enabled: true
    description: Robotics - Tech.eu robotics news
  mit_tech_review:
    url: https://www.technologyreview.com/c/computing/rss/
    type: rss
    category: Media
    enabled: true
    description: Computing – MIT Technology Review
  techrepublic_ai:
    url: https://www.techrepublic.com/rssfeeds/topic/artificial-intelligence/
    type: rss
    category: Media
    enabled: true
    description: Artificial Intelligence on TechRepublic
  tech_xplore:
    url: https://techxplore.com/rss-feed/machine-learning-ai-news/
    type: rss
    category: Media
    enabled: true
    description: Tech Xplore - News on Artificial Intelligence and Machine Learning
  phys_org_ai:
    url: https://phys.org/rss-feed/technology-news/machine-learning-ai/
    type: rss
    category: Media
    enabled: true
    description: News on Artificial Intelligence and Machine Learning - Phys.org
  the_decoder:
    url: https://the-decoder.com/feed/
    type: rss
    category: Media
    enabled: true
    description: THE DECODER - Artificial Intelligence News, Business, Research
  guardian_ai:
    url: https://www.theguardian.com/technology/artificialintelligenceai/rss
    type: rss
    category: Media
    enabled: true
    description: Artificial intelligence (AI) | The Guardian
  neural_thenextweb:
    url: https://thenextweb.com/neural/feed
    type: rss
    category: Media
    enabled: true
    description: Neural - The Next Web AI section
  the_register:
    url: https://www.theregister.com/software/ai_ml/headlines.atom
    type: rss
    category: Media
    enabled: true
    description: The Register - Software AI + ML
  the_verge:
    url: https://www.theverge.com/rss/index.xml
    type: rss
    category: Media
    enabled: true
    description: The Verge - Technology news and media
  wired_ai:
    url: https://www.wired.com/feed/category/artificial-intelligence/rss
    type: rss
    category: Media
    enabled: true
    description: The Artificial Intelligence Database - WIRED
