sources:
  huggingface_blog:
    url: https://huggingface.co/blog/feed.xml
    type: rss
    category: Open Source
    enabled: true
    description: Hugging Face official blog - very active with latest AI/ML developments
  pytorch_blog:
    url: https://pytorch.org/blog/feed.xml
    type: rss
    category: Open Source
    enabled: true
    description: PyTorch official blog
  tensorflow_blog:
    url: https://blog.tensorflow.org/feeds/posts/default
    type: rss
    category: Open Source
    enabled: true
    description: TensorFlow official blog
  creative_commons_blog:
    url: https://creativecommons.org/feed/
    type: rss
    category: Open Source
    enabled: true
    description: Creative Commons Blog - open culture and licensing updates
    legal_note: CC BY 4.0 - open sharing
  mlops_community:
    url: https://mlops.community/feed/
    type: rss
    category: Open Source
    enabled: true
    description: MLOps Community discussions
  ai_weirdness:
    url: https://www.aiweirdness.com/rss/
    type: rss
    category: Open Source
    enabled: true
    description: AI Weirdness - The strange side of machine learning
  aihub:
    url: https://aihub.org/feed?cat=-473
    type: rss
    category: Open Source
    enabled: true
    description: ΑΙhub - Connecting the AI community and the world
  berkeley_ai_blog:
    url: https://bair.berkeley.edu/blog/feed.xml
    type: rss
    category: Open Source
    enabled: true
    description: The Berkeley Artificial Intelligence Research Blog
  python_insider:
    url: https://feeds.feedburner.com/PythonInsider
    type: rss
    category: Open Source
    enabled: true
    description: Python Insider - Python core development news
  nicholas_carlini:
    url: https://nicholas.carlini.com/writing/feed.xml
    type: rss
    category: Open Source
    enabled: true
    description: Nicholas Carlini - Security and AI research blog
  cmu_ml_blog:
    url: https://blog.ml.cmu.edu/feed
    type: rss
    category: Open Source
    enabled: true
    description: Machine Learning Blog | ML@CMU | Carnegie Mellon University
  david_stutz:
    url: https://davidstutz.de/category/blog/feed
    type: rss
    category: Open Source
    enabled: true
    description: Blog Archives • David Stutz - Robust and trustworthy AI research
  deep_shallow:
    url: https://deep-and-shallow.com/feed
    type: rss
    category: Open Source
    enabled: true
    description: Deep & Shallow - Musings about data and AI
  elastic_blog:
    url: https://www.elastic.co/blog/feed
    type: rss
    category: Open Source
    enabled: true
    description: Elastic Blog - Elasticsearch, Kibana, and ELK Stack
  explosion_ai:
    url: https://explosion.ai/feed
    type: rss
    category: Open Source
    enabled: true
    description: Explosion - NLP tools and spaCy creators
  fast_ai:
    url: https://www.fast.ai/index.xml
    type: rss
    category: Open Source
    enabled: true
    description: fast.ai - Making neural nets uncool again
  gradient_flow:
    url: https://gradientflow.com/feed/
    type: rss
    category: Open Source
    enabled: true
    description: Gradient Flow - Unlocking Data and AI
  chip_huyen:
    url: https://huyenchip.com/feed
    type: rss
    category: Open Source
    enabled: true
    description: Chip Huyen - ML production and engineering blog
  machine_intelligence_institute:
    url: http://feeds.feedburner.com/miriblog
    type: rss
    category: Open Source
    enabled: true
    description: Blog – Machine Intelligence Research Institute
  import_ai:
    url: https://jack-clark.net/feed
    type: rss
    category: Open Source
    enabled: true
    description: Import AI - Weekly AI newsletter by Jack Clark
  jmlr:
    url: https://www.jmlr.org/jmlr.xml
    type: rss
    category: Open Source
    enabled: true
    description: JMLR - Journal of Machine Learning Research
  machine_learning_mastery:
    url: https://machinelearningmastery.com/blog/feed
    type: rss
    category: Open Source
    enabled: true
    description: Blog – Machine Learning Mastery - Making developers awesome at ML
  samuele_mazzanti:
    url: https://medium.com/feed/@mazzanti.sam
    type: rss
    category: Open Source
    enabled: true
    description: Stories by Samuele Mazzanti on Medium - Data science insights
  max_woolf:
    url: https://minimaxir.com/post/index.xml
    type: rss
    category: Open Source
    enabled: true
    description: Max Woolf's Blog - Data science and AI insights
  neptune_ai:
    url: https://neptune.ai/blog/feed
    type: rss
    category: Open Source
    enabled: true
    description: Blog – neptune.ai - MLOps and experiment tracking
  paperspace_blog:
    url: https://blog.paperspace.com/rss/
    type: rss
    category: Open Source
    enabled: true
    description: Paperspace Blog - Machine Learning, AI, Cloud GPUs
  pyimagesearch:
    url: https://pyimagesearch.com/blog/feed
    type: rss
    category: Open Source
    enabled: true
    description: PyImageSearch - Computer Vision, Deep Learning, and OpenCV
  python_peps:
    url: https://www.python.org/dev/peps/peps.rss
    type: rss
    category: Open Source
    enabled: true
    description: Newest Python PEPs - Python Enhancement Proposals
  r_bloggers:
    url: https://feeds.feedburner.com/RBloggers
    type: rss
    category: Open Source
    enabled: true
    description: R-bloggers - R news and tutorials
  sciencedaily_neural:
    url: https://www.sciencedaily.com/rss/computers_math/neural_interfaces.xml
    type: rss
    category: Open Source
    enabled: true
    description: Neural Interfaces News -- ScienceDaily
  sciencedaily_robotics:
    url: https://www.sciencedaily.com/rss/computers_math/robotics.xml
    type: rss
    category: Open Source
    enabled: true
    description: Robotics Research News -- ScienceDaily
  sciencedaily_ai:
    url: https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml
    type: rss
    category: Open Source
    enabled: true
    description: Artificial Intelligence News -- ScienceDaily
  stanford_ai_lab:
    url: http://ai.stanford.edu/blog/feed.xml
    type: rss
    category: Open Source
    enabled: true
    description: The Stanford AI Lab Blog
  ai_summer:
    url: https://theaisummer.com/feed.xml
    type: rss
    category: Open Source
    enabled: true
    description: AI Summer - Learn Deep Learning and Artificial Intelligence
  towards_ai:
    url: https://pub.towardsai.net/feed
    type: rss
    category: Open Source
    enabled: true
    description: Towards AI - Medium publication for AI content
  weights_biases:
    url: https://wandb.ai/fully-connected/rss.xml
    type: rss
    category: Open Source
    enabled: true
    description: Weights & Biases Fully Connected - ML experiment tracking
