sources:
  arxiv:
    url: https://rss.arxiv.org/rss/cs.AI+cs.LG+cs.CV+cs.CL
    type: rss
    category: Research
    enabled: true
    description: ArXiv AI papers - comprehensive feed
    legal_note: Open access research - public domain