sources:
  ira_news:
    category: Telugu Media
    description: Ira News
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://iranewspaper.com/feed
  telugu_bullet:
    category: Telugu Media
    description: Telugu Bullet
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugubulletin.com/movies/feed
  mana_telangana:
    category: Telugu Media
    description: Mana Telangana - Leading Telugu Daily News
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://manatelangana.news/feed
  nava_telangana:
    category: Telugu Media
    description: Nava Telangana - News analysis and innovative stories
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://navatelangana.com/feed
  telugu_bullet_main:
    category: Telugu Media
    description: Telugu Bullet - Latest Telugu news from AP and Telangana
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugu.telugubullet.com/feed
  ntv_telugu:
    category: Telugu Media
    description: NTV Telugu - Regional Telugu news channel
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://ntvtelugu.com/feed
  visala_andhra:
    category: Telugu Media
    description: Visala Andhra - Current news from Telugu regions
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://visalaandhra.com/feed
  oktelugu:
    category: Telugu Media
    description: OK Telugu - Latest news about Telugu people worldwide
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://oktelugu.com/feed
  telugu_bulletin:
    category: Telugu Media
    description: Telugu Bulletin - Politics and Movies content
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugubulletin.com/feed
  telugu_stop:
    category: Telugu Media
    description: Telugu Stop Media - Leading news source for Telugu People
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugustop.com/feed
  v6_velugu:
    category: Telugu Media
    description: V6 Velugu - 24 hour Telugu Satellite News Broadcaster
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://v6velugu.com/feed
  telugu_rajyam:
    category: Telugu Media
    description: Telugu Rajyam - Unalloyed news and current affairs
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugurajyam.com/feed
  adya_news:
    category: Telugu Media
    description: Adya News Telugu - Latest News Updates in Telugu
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://adya.news/telugu/feed
  namasthe_telangana:
    category: Telugu Media
    description: Namasthe Telangana - Breaking news and updates
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://ntnews.com/news/feed
  telugu360:
    category: Telugu Media
    description: Telugu360 - Tollywood and Telugu film news
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugu360.com/feed
  gulte:
    category: Telugu Media
    description: Gulte - Breaking News of Andhra Pradesh and Telugu Movies
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugu.gulte.com/feed
  telugu_mirchi:
    category: Telugu Media
    description: Telugu Mirchi - Latest Telugu movie and cinema news
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugumirchi.com/telugu/feed
  namasteandhra:
    category: Telugu Media
    description: Namasteandhra - Sports, politics, entertainment discussions
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://namasteandhra.com/feed
  prajatantra_news:
    category: Telugu Media
    description: Prajatantra News - Breaking News from Telangana and AP
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://prajatantranews.com/feed
  newsorbit:
    category: Telugu Media
    description: NewsOrbit - Unbiased news for AP and Telangana
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://newsorbit.com/feed
  telugu_post:
    category: Telugu Media
    description: Telugu Post - Latest news updates
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://telugupost.com/latest-news/feed
  ten_tv:
    category: Telugu Media
    description: 10 TV - LIVE News in Telugu on Politics and Business
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://10tv.in/latest/feed
  manalokam:
    category: Telugu Media
    description: Manalokam - Ethical and responsible journalism
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://manalokam.com/news/feed
  andhrajyothi:
    category: Telugu Media
    description: Andhrajyothi - No.1 Telugu 24/7 news channel
    enabled: true
    legal_note: Please check individual source for republication rights
    type: rss
    url: https://andhrajyothy.com/rss/feed.xml
