// Daily AI Times — article data
window.TICKER_ITEMS = [
  { tag: "BREAKING", text: "OpenAI reorganizes research division as Weil and Peebles depart for venture fund" },
  { tag: "MARKETS", text: "NVIDIA closes +2.4% on Q1 earnings beat; hyperscaler capex guidance raised" },
  { tag: "LIVE", text: "Anthropic hosts developer keynote — streaming from San Francisco, 2:00 PM PT" },
  { tag: "POLICY", text: "EU AI Act Phase II enforcement begins; first audits scheduled for Q3" },
  { tag: "RESEARCH", text: "DeepMind publishes AlphaProof-2: automated theorem proving reaches IMO gold level" },
];

window.ARTICLES = {
  lead: {
    id: "lead",
    kicker: "THE EXIT",
    section: "Industry",
    headline: "Two OpenAI Executives Leave to Start Venture Fund, Citing ‘The Model Is The Product’",
    deck: "Kevin Weil and Bill Peebles, who together shepherded product and video research, will raise a $1.8 billion fund aimed at what they describe as a post-application era in artificial intelligence.",
    byline: "By MARA CHEN and DEVON OKAFOR",
    dateline: "SAN FRANCISCO, April 17",
    time: "2 hr ago",
    body: [
      "Two senior figures at OpenAI are departing the company to launch an investment firm focused on what they call a post-application era of artificial intelligence, according to three people familiar with the plans.",
      "Kevin Weil, the former head of product, and Bill Peebles, who led the Sora video research group, told colleagues on Thursday that they had raised $1.8 billion in commitments from sovereign wealth funds, university endowments, and a small group of individual limited partners.",
      "The new firm, tentatively named Throughline, will invest almost exclusively in teams building what the pair describe in a private pitch document as ‘native model products’ — software in which the underlying model is not a feature but the entire surface area of the experience.",
      "‘The application layer as we have known it for fifteen years is going to compress very quickly,’ Mr. Peebles said in an interview. ‘We want to back the founders who are building for the moment after that compression, not before.’",
      "A spokeswoman for OpenAI confirmed the departures but declined to comment on the fund. The company has been shedding what chief executive Sam Altman previously described as ‘side quests’ as it concentrates resources on a smaller slate of flagship efforts.",
    ],
    hero: { type: "photo", caption: "Kevin Weil, left, and Bill Peebles at an industry summit in February. The pair have worked together since 2023.", credit: "Photo illustration for the Daily AI Times" },
  },
  swing: {
    id: "swing",
    kicker: "ANALYSIS",
    headline: "Research Labs Are Quietly Shrinking. Here Is What That Means.",
    byline: "By ANDREA VOSS",
    body: [
      "For more than two years, the prevailing theory inside frontier research labs has been that bigger organizations beget bigger models. That theory is being tested.",
      "Three of the five leading labs have reduced headcount in their pure-research divisions over the past nine months, according to internal documents reviewed by the Daily AI Times. At the same time, their product and infrastructure teams have grown — in some cases by more than forty percent.",
      "The shift has alarmed some veteran researchers, who argue that compressing the timeline from publication to deployment sacrifices a kind of intellectual slack that produced the breakthroughs of the last decade.",
      "‘You cannot schedule a phase transition,’ one researcher, who requested anonymity to speak about internal strategy, said. ‘You can only fund the conditions under which one might occur.’",
      "Others see the consolidation as overdue. ‘The era of publishing a paper every six weeks is ending,’ said a vice president at one of the labs. ‘The work is now the product. The product is the work.’",
    ],
  },
  stories: [
    {
      id: "s1", section: "Research", headline: "NIH-Backed Study Shrinks CRISPR Payload to Fit in a Single Viral Vector Using AI-Guided Protein Design",
      byline: "By SAMI OKONKWO",
      summary: "The collaboration between three national laboratories and a small model company produced a variant 38 percent smaller than the wild-type enzyme, opening the door to single-dose in-vivo gene editing.",
      time: "4 hr ago", type: "text",
    },
    {
      id: "s2", section: "Tools", headline: "Amazon Expands Nova Multimodal Embeddings to Video, Audio, and Long-Form Documents",
      byline: "By RUTH PATEL",
      summary: "The release closes a gap with Google’s Gemini embedding stack and adds first-class support for semantic search across three-hour video archives.",
      time: "5 hr ago", type: "text",
    },
    {
      id: "s3", section: "Research", headline: "On-Device Agents Without the Cloud: NVIDIA ‘NanoClaw’ Reference Architecture Explained",
      byline: "By LUCA HERNÁNDEZ",
      summary: "Agents that remember what you worked on yesterday, run locally, and still call remote tools — a technical reading of the new reference design, and where it falls short of the hype.",
      time: "6 hr ago", type: "video", duration: "8:42",
    },
    {
      id: "s4", section: "Tools", headline: "Isabelle/HOL: The Quiet Proof Assistant Behind the Nitro Isolation Engine",
      byline: "By JEREMIAH BLAND",
      summary: "An unlikely tool — first written in the 1980s — is having a renaissance as security teams formally verify the hypervisors underneath AI training clusters.",
      time: "6 hr ago", type: "text",
    },
    {
      id: "s5", section: "Industry", headline: "Cost-Efficient Custom Text-to-SQL at Scale: Notes From a Year in Production",
      byline: "By WEN-LI ZHAO",
      summary: "A frank accounting of what a mid-sized analytics company learned after switching to a distilled in-house model for database queries.",
      time: "7 hr ago", type: "text",
    },
    {
      id: "s6", section: "Tools", headline: "Roblox’s In-World Assistant Gets Agentic Tools to Plan, Build, and Test Games",
      byline: "By INGRID SODERBERG",
      summary: "The update pushes agentic workflows into the hands of teenage developers, and raises fresh questions about moderation at the intersection of code generation and user-generated content.",
      time: "8 hr ago", type: "photo",
    },
    {
      id: "s7", section: "Research", headline: "A New Vision Pipeline That Does Not Assume Pixels: Rosalind-2 at ICML",
      byline: "By MARA CHEN",
      summary: "The paper argues that treating images as implicit fields rather than grids yields better sample efficiency on medical imagery, with striking early results in ophthalmology.",
      time: "9 hr ago", type: "text",
    },
    {
      id: "s8", section: "Policy", headline: "Open Letter From 100 Business Leaders Urges Coordinated Response to AI-Enabled Cyber Threats",
      byline: "By DEVON OKAFOR",
      summary: "The letter, signed by chief information security officers at Fortune 500 firms, requests a public-private information sharing protocol within the year.",
      time: "10 hr ago", type: "text",
    },
    {
      id: "s9", section: "Industry", headline: "AWS and Johns Hopkins Engineering Announce a Public Database for AI-Assisted Antibody Design",
      byline: "By SAMI OKONKWO",
      summary: "The database will release new structures on a rolling basis and pairs each with the model prompt and scoring function that produced it.",
      time: "11 hr ago", type: "text",
    },
    {
      id: "s10", section: "Research", headline: "AI, Explained Without the Metaphors: A Fundamentals Series",
      byline: "By THE EDITORS",
      summary: "What a large language model actually does, in plain language, without saying that anything is ‘like a brain.’ Part one of five.",
      time: "12 hr ago", type: "text",
    },
    {
      id: "s11", section: "Tools", headline: "Agents SDK Adds Durable Execution, Crash Recovery, and Deterministic Replay",
      byline: "By RUTH PATEL",
      summary: "The long-awaited durability update answers the top issue filed on the project: what happens when your agent is three hours into a task and the process dies.",
      time: "13 hr ago", type: "text",
    },
    {
      id: "s12", section: "Industry", headline: "Cloudflare Opens an ‘Agent Cloud’ Aimed at Enterprise Workflows",
      byline: "By INGRID SODERBERG",
      summary: "The platform extends Workers with long-running execution, state sharing, and a policy layer for scoped access to internal systems.",
      time: "14 hr ago", type: "text",
    },
    {
      id: "s13", section: "Research", headline: "NVIDIA Omniverse Gets a Physical AI SDK. The Implication: Fewer Simulators, More Unified Scenes.",
      byline: "By LUCA HERNÁNDEZ",
      summary: "A consolidation move that puts pressure on a constellation of smaller simulation companies to differentiate on something other than physics fidelity.",
      time: "16 hr ago", type: "video", duration: "4:11",
    },
    {
      id: "s14", section: "Industry", headline: "Meta Reorganizes Reality Labs Around a Single On-Device Foundation Model",
      byline: "By DEVON OKAFOR",
      summary: "The move consolidates three separate research tracks and puts a single post-training team in charge of everything from headset assistants to smart-glass captions.",
      time: "17 hr ago", type: "text",
    },
    {
      id: "s15", section: "Tools", headline: "Hugging Face Adds Native Support for Structured Outputs Across 400 Community Models",
      byline: "By WEN-LI ZHAO",
      summary: "The update standardizes JSON-schema and grammar-constrained decoding across models that previously each shipped their own loose conventions.",
      time: "18 hr ago", type: "text",
    },
    {
      id: "s16", section: "Policy", headline: "California Bill Would Require Provenance Watermarks on All Synthetic Media Used in Ads",
      byline: "By JEREMIAH BLAND",
      summary: "The proposal, narrower than last year’s failed omnibus, targets only commercial advertising and leaves newsroom and artistic uses untouched.",
      time: "19 hr ago", type: "text",
    },
    {
      id: "s17", section: "Research", headline: "A Second Look at the ‘Reasoning Tax’: When Chain-of-Thought Actually Slows Things Down",
      byline: "By MARA CHEN",
      summary: "A careful ablation from ETH Zürich argues the benefits of explicit reasoning steps are narrower than the literature has claimed, especially for well-formed code tasks.",
      time: "20 hr ago", type: "photo",
    },
    {
      id: "s18", section: "Industry", headline: "Databricks Buys a Small Agents Startup to Anchor Its Enterprise Workflow Push",
      byline: "By INGRID SODERBERG",
      summary: "Terms were not disclosed. The acquired team, seven engineers, will ship a managed orchestration layer into the Databricks runtime within the quarter.",
      time: "21 hr ago", type: "text",
    },
    {
      id: "s19", section: "Tools", headline: "The Return of the Monorepo: Why AI-Assisted Refactors Change the Math",
      byline: "By SAMI OKONKWO",
      summary: "Engineering leaders at three large companies say agent-assisted mass edits have made the long-standing cost of monorepo sprawl suddenly tractable.",
      time: "22 hr ago", type: "text",
    },
    {
      id: "s20", section: "Research", headline: "Speech Models Quietly Overtake Humans on a Standard Phonetic Transcription Benchmark",
      byline: "By RUTH PATEL",
      summary: "The result, from a team at CMU and a small startup in Montréal, was reported on a dataset that has been considered a ceiling for a decade.",
      time: "23 hr ago", type: "text",
    },
    {
      id: "s21", section: "Policy", headline: "FTC Opens Informal Inquiry Into Training-Data Licensing Practices at Three Major Labs",
      byline: "By JEREMIAH BLAND",
      summary: "The inquiry, which the agency characterized as ‘fact-finding,’ focuses on undisclosed side-letters that governed pre-2024 dataset deals.",
      time: "1 day ago", type: "text",
    },
  ],
  opinion: [
    { id: "o1", title: "The Case Against Another Benchmark", author: "Harper Linde", excerpt: "We are measuring the wrong things, with increasing precision." },
    { id: "o2", title: "What Senior Engineers Owe the Junior Ones Now", author: "Owen Matsuda", excerpt: "A reading list is not a training plan. Neither is a chatbot." },
    { id: "o3", title: "Why I Stopped Trusting Model Cards", author: "Priya Ramachandran", excerpt: "The disclosure document we adopted in 2019 is no longer serving anyone." },
  ],
  markets: [
    { ticker: "NVDA", px: "1,184.22", ch: "+2.4%", up: true },
    { ticker: "MSFT", px: "498.10", ch: "+0.8%", up: true },
    { ticker: "GOOGL", px: "214.67", ch: "-0.3%", up: false },
    { ticker: "META", px: "722.94", ch: "+1.1%", up: true },
    { ticker: "AMD",  px: "208.55", ch: "-1.6%", up: false },
    { ticker: "TSM",  px: "241.08", ch: "+0.9%", up: true },
  ],
  weather: [
    { city: "SAN FRANCISCO",  hi: 62, lo: 51, cond: "Fog, then sun" },
    { city: "NEW YORK",       hi: 71, lo: 58, cond: "Partly cloudy" },
    { city: "LONDON",         hi: 59, lo: 48, cond: "Scattered rain" },
    { city: "TOKYO",          hi: 68, lo: 55, cond: "Clear" },
  ],
};
